In [1]:
pip install lightgbm

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\ninou\anaconda3\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy as np
import pandas as pd
import urllib
import lightgbm as lgb

from lightgbm import LGBMClassifier
from sklearn.model_selection import train_test_split

from sklearn import metrics
from sklearn.metrics import accuracy_score

In [3]:
#data = pd.read_csv("C:\\Users\\ninou\\Desktop\\breast_canser.cvs")
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/spambase/spambase.data"

raw_data = urllib.request.urlopen(url)
dataset = np.loadtxt(raw_data, delimiter = ',')

print(dataset[0])


[  0.      0.64    0.64    0.      0.32    0.      0.      0.      0.
   0.      0.      0.64    0.      0.      0.      0.32    0.      1.29
   1.93    0.      0.96    0.      0.      0.      0.      0.      0.
   0.      0.      0.      0.      0.      0.      0.      0.      0.
   0.      0.      0.      0.      0.      0.      0.      0.      0.
   0.      0.      0.      0.      0.      0.      0.778   0.      0.
   3.756  61.    278.      1.   ]


In [4]:
X = dataset[:,0:48]
Y = dataset[:, -1]
print(Y)
print(X)

[1. 1. 1. ... 0. 0. 0.]
[[0.   0.64 0.64 ... 0.   0.   0.  ]
 [0.21 0.28 0.5  ... 0.   0.   0.  ]
 [0.06 0.   0.71 ... 0.06 0.   0.  ]
 ...
 [0.3  0.   0.3  ... 1.2  0.   0.  ]
 [0.96 0.   0.   ... 0.32 0.   0.  ]
 [0.   0.   0.65 ... 0.65 0.   0.  ]]


In [5]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = .33, random_state = 17)
print(len(X_train))
print(len(X_test))
print(Y_train)
print(Y_test)

3082
1519
[0. 1. 0. ... 1. 0. 0.]
[1. 1. 1. ... 1. 0. 1.]


In [6]:
model = LGBMClassifier()
model.fit(X_train, Y_train)
print(model)
pred = model.predict(X_test)
print(pred)
Y_expect = Y_test
print(accuracy_score(Y_expect, pred))

LGBMClassifier()
[1. 1. 1. ... 0. 0. 1.]
0.9361421988150099
