In [1]:
import numpy as np
import pandas as pd
import urllib
import sklearn
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split

from sklearn import metrics
from sklearn.metrics import accuracy_score

In [2]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/spambase/spambase.data"

raw_data = urllib.request.urlopen(url)

dataset = np.loadtxt(raw_data, delimiter = ',')
print(dataset[0])

[  0.      0.64    0.64    0.      0.32    0.      0.      0.      0.
   0.      0.      0.64    0.      0.      0.      0.32    0.      1.29
   1.93    0.      0.96    0.      0.      0.      0.      0.      0.
   0.      0.      0.      0.      0.      0.      0.      0.      0.
   0.      0.      0.      0.      0.      0.      0.      0.      0.
   0.      0.      0.      0.      0.      0.      0.778   0.      0.
   3.756  61.    278.      1.   ]


In [3]:
X = dataset[:,0:48]
Y = dataset[:, -1]
print(Y)
print(X)



[1. 1. 1. ... 0. 0. 0.]
[[0.   0.64 0.64 ... 0.   0.   0.  ]
 [0.21 0.28 0.5  ... 0.   0.   0.  ]
 [0.06 0.   0.71 ... 0.06 0.   0.  ]
 ...
 [0.3  0.   0.3  ... 1.2  0.   0.  ]
 [0.96 0.   0.   ... 0.32 0.   0.  ]
 [0.   0.   0.65 ... 0.65 0.   0.  ]]


In [4]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = .33, random_state = 17)
print(len(X_train))
print(len(X_test))
print(Y_train)
print(Y_test)

3082
1519
[0. 1. 0. ... 1. 0. 0.]
[1. 1. 1. ... 1. 0. 1.]


In [5]:
BernNB = BernoulliNB(binarize = True)
BernNB.fit(X_train, Y_train)
print(BernNB)

Y_expect = Y_test
Y_pred = BernNB.predict(X_test)
print(Y_expect)
print(Y_pred)
print(accuracy_score(Y_expect, Y_pred))

BernoulliNB(binarize=True)
[1. 1. 1. ... 1. 0. 1.]
[1. 1. 1. ... 0. 0. 1.]
0.8558262014483212


In [6]:
MultiNB = MultinomialNB()

MultiNB.fit(X_train, Y_train)
print(MultiNB)
Y_pred = MultiNB.predict(X_test)
print(accuracy_score(Y_expect, Y_pred))

MultinomialNB()
0.8736010533245556


In [7]:
GausNB = GaussianNB()
GausNB.fit(X_train, Y_train)
print(GausNB)

Y_pred = GausNB.predict(X_test)
print(accuracy_score(Y_expect, Y_pred))


GaussianNB()
0.8130348913759052


In [8]:
BernNB = BernoulliNB(binarize = 0.1)
BernNB.fit(X_train, Y_train)
print(BernNB)
Y_expect = Y_test
Y_pred = BernNB.predict(X_test)
print(accuracy_score(Y_expect, Y_pred))

BernoulliNB(binarize=0.1)
0.8953258722843976
